
spring:
  application:
    name: hello-hilla-grid

  datasource:
    url: jdbc:h2:mem:gridDb

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        "[show_sql]": true
        "[use_sql_comments]": true
        "[format_sql]": true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        type: trace
