INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Agnes Depot', 'Martinica');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Arrierito Inc', 'La Almunia de Doña Godina');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Brisa Global', 'Valparaíso');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Tierra Verde S.A.', 'Montevideo');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Delicias del Sur', 'Arequipa');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Sol y Sombra Ltda.', 'Cali');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Aurora Trading Co.', 'San Miguel de Tucumán');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Cosechas Andinas', 'Cuenca');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Puerto Fresco Inc.', 'Cartagena');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Altura Export', 'Oruro');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('Verde Limón S.A.', 'Corrientes');
INSERT INTO suppliers(supplier_name, headquarter_city) VALUES('La Casa del Grano', 'Saltillo');

INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Stirrup M ', 'Headphones', 19.9, CURRENT_DATE, 1);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('New Stirrup M', 'Headphones', 25.9, CURRENT_DATE, 1);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('New Action Stirrup M', 'Headphones', 29.9, CURRENT_DATE, 1);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Silver Sound Basic', 'Walkman', 35, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Silver Sound Plus', 'Walkman', 45, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Silver Sound Pro', 'Walkman', 59.9, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('BassFlow Mini', 'Headphones', 18.5, CURRENT_DATE, 3);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('BassFlow Max', 'Headphones', 32.0, CURRENT_DATE, 3);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('EchoPro Lite', 'Speakers', 40.0, CURRENT_DATE, 4);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('EchoPro X', 'Speakers', 65.0, CURRENT_DATE, 4);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Retro Tape Classic', 'Walkman', 28.5, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Retro Tape Deluxe', 'Walkman', 39.9, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('PulseFit Basic', 'Headphones', 22.9, CURRENT_DATE, 5);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('PulseFit Advanced', 'Headphones', 36.5, CURRENT_DATE, 5);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Neon Beats M1', 'Speakers', 55.0, CURRENT_DATE, 1);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Neon Beats M2', 'Speakers', 60.0, CURRENT_DATE, 1);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('AuroraPod X', 'Headphones', 24.4, CURRENT_DATE, 3);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('AuroraPod X+', 'Headphones', 30.0, CURRENT_DATE, 3);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('WaveMaster S', 'Walkman', 33.3, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('WaveMaster X', 'Walkman', 47.0, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('StreamBox Go', 'Speakers', 49.5, CURRENT_DATE, 4);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('StreamBox Pro', 'Speakers', 69.9, CURRENT_DATE, 4);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('BeatBuds Z', 'Headphones', 20.0, CURRENT_DATE, 1);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('BeatBuds Z+', 'Headphones', 27.0, CURRENT_DATE, 1);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('SoundSphere Mini', 'Speakers', 38.9, CURRENT_DATE, 5);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('SoundSphere Pro', 'Speakers', 58.0, CURRENT_DATE, 5);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('EchoLite XS', 'Headphones', 16.9, CURRENT_DATE, 4);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('EchoLite XS+', 'Headphones', 21.5, CURRENT_DATE, 4);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('RetroBox Basic', 'Walkman', 26.5, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('RetroBox Premium', 'Walkman', 44.0, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('BassRunner M', 'Headphones', 29.9, CURRENT_DATE, 3);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('BassRunner XL', 'Headphones', 35.0, CURRENT_DATE, 3);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Neon Pulse A1', 'Headphones', 23.0, CURRENT_DATE, 1);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Neon Pulse A2', 'Headphones', 28.5, CURRENT_DATE, 1);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('SoundLoop Mini', 'Speakers', 31.0, CURRENT_DATE, 4);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('SoundLoop Ultra', 'Speakers', 68.0, CURRENT_DATE, 4);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('AudioCore Classic', 'Walkman', 37.5, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('AudioCore Elite', 'Walkman', 52.0, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('BeatMax Solo', 'Headphones', 26.9, CURRENT_DATE, 3);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('BeatMax Duo', 'Headphones', 34.9, CURRENT_DATE, 3);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('GrooveCube S', 'Speakers', 45.0, CURRENT_DATE, 5);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('GrooveCube XL', 'Speakers', 62.0, CURRENT_DATE, 5);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Cassette Pro 90', 'Walkman', 40.5, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('Cassette Pro 120', 'Walkman', 48.0, CURRENT_DATE, 2);
INSERT INTO products(name, category, price, date_added, supplier_id) VALUES('StudioBuds Lite', 'Headphones', 19.0, CURRENT_DATE, 1);
